name: 'Rebol-SQLite CI'
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  windows:
    strategy:
      fail-fast: true
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Siskin Builder
      uses: oldes/install-siskin@v0.17.0

    - name: Build 64bit Rebol SQLite extension
      run: ./siskin Rebol-SQLite.nest --msvc -o sqlite-windows-x64.rebx sqlite-x64

    - name: Install Rebol for extension test
      uses: oldes/install-rebol@v3.17.0

    - name: Test SQLite extension
      run:  ./rebol3 ci-test.r3

    ###############################################################################
    # Collecting build artifacts...
    - uses: actions/upload-artifact@v3
      with:
        name: Rebol-SQLite-CI-${{github.run_id}}
        path: ./sqlite-windows-x64.rebx

  linux:
#   strategy:
#     fail-fast: true
#     matrix:
#       os: [ubuntu-18.04]
#       #os: [ubuntu-20.04, ubuntu-18.04]
#
#   runs-on: ${{ matrix.os }}
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Siskin Builder
        uses: oldes/install-siskin@v0.17.0

#      - name: Build 32bit Rebol SQLite extension
#        run: ./siskin Rebol-SQLite.nest -o sqlite-linux-x86.rebx sqlite-x86

      - name: Build 64bit Rebol SQLite extension
        run: ./siskin Rebol-SQLite.nest -o sqlite-linux-x64.rebx sqlite-x64

      - name: Install Rebol for extension test
        uses: oldes/install-rebol@v3.17.0

      - name: Test SQLite extension
        run:  ./rebol3 ci-test.r3

      - name: Compress 64bit Rebol SQLite extension
        run:  gzip -9 ./sqlite-linux-x64.rebx

      - uses: actions/upload-artifact@v3
        with:
          name: Rebol-SQLite-CI-${{github.run_id}}
          path: ./sqlite-linux-*

  macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Siskin Builder
        uses: oldes/install-siskin@v0.17.0

      - name: Build 64bit Rebol SQLite extension
        run: ./siskin Rebol-SQLite.nest -o sqlite-macos-x64.rebx sqlite-x64

      - name: Install Rebol for extension test
        uses: oldes/install-rebol@v3.17.0

      - name: Test SQLite extension
        run:  ./rebol3 ci-test.r3

      - name: Compress 64bit Rebol SQLite extension
        run:  gzip -9 ./sqlite-macos-x64.rebx

      - uses: actions/upload-artifact@v3
        with:
          name: Rebol-SQLite-CI-${{github.run_id}}
          path: ./sqlite-macos-*